---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
  labels:
    app: spring-petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
      - name: spring-petclinic
        image: altaira/pet-clinic:7e31d7ae2671c24ba67fc7f06d47986de93aa6ad
#        env:
#          - name: SPRING_PROFILES_ACTIVE
#            value: postgres
